# Generated by Django 2.0.1 on 2019-01-30 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UdemyCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_time', models.TimeField(null=True)),
                ('avg_rating', models.FloatField(null=True)),
                ('completion_ratio', models.FloatField(null=True)),
                ('created', models.DateField(null=True)),
                ('description', models.TextField(null=True)),
                ('favorite_time', models.TimeField(null=True)),
                ('headline', models.TextField(null=True)),
                ('image_100X100', models.CharField(max_length=1024, null=True)),
                ('image_125_H', models.CharField(max_length=1024, null=True)),
                ('image_200_H', models.CharField(max_length=1024, null=True)),
                ('image_240X135', models.CharField(max_length=1024, null=True)),
                ('image_304X171', models.CharField(max_length=1024, null=True)),
                ('image_48X27', models.CharField(max_length=1024, null=True)),
                ('image_50X50', models.CharField(max_length=1024, null=True)),
                ('image_75X75', models.CharField(max_length=1024, null=True)),
                ('image_96X54', models.CharField(max_length=1024, null=True)),
                ('is_in_any_ufb_content_collection', models.NullBooleanField()),
                ('is_paid', models.NullBooleanField()),
                ('is_private', models.NullBooleanField()),
                ('is_whitelisted', models.NullBooleanField()),
                ('locale', models.CharField(max_length=100, null=True)),
                ('num_lectures', models.IntegerField(null=True)),
                ('num_quizzes', models.IntegerField(null=True)),
                ('num_reviews', models.IntegerField(null=True)),
                ('num_subscribers', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('status_label', models.CharField(max_length=30, null=True)),
                ('title', models.CharField(max_length=1024, null=True)),
                ('url', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UdemyCourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('title_cleaned', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UdemyCourseSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('title_cleaned', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentprovider.UdemyCourseCategory')),
            ],
        ),
        migrations.CreateModel(
            name='UdemyInstructedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='contentprovider.UdemyCourse')),
            ],
        ),
        migrations.CreateModel(
            name='UdemyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('created', models.DateField()),
                ('has_activated', models.NullBooleanField()),
                ('image_100X100', models.CharField(max_length=1024)),
                ('image_125_H', models.CharField(max_length=1024)),
                ('image_200_H', models.CharField(max_length=1024)),
                ('image_50X50', models.CharField(max_length=1024)),
                ('image_75X75', models.CharField(max_length=1024)),
                ('is_disabled', models.NullBooleanField()),
                ('is_followed', models.NullBooleanField()),
                ('is_generated', models.NullBooleanField()),
                ('job_title', models.CharField(max_length=100)),
                ('locale', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('num_subscribed_courses', models.IntegerField()),
                ('surname', models.CharField(max_length=100)),
                ('time_zone', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1024)),
                ('url_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='udemyinstructedby',
            name='instructors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='contentprovider.UdemyUser'),
        ),
        migrations.AddField(
            model_name='udemycourse',
            name='primary_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_category', to='contentprovider.UdemyCourseCategory'),
        ),
        migrations.AddField(
            model_name='udemycourse',
            name='primary_subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_subcategory', to='contentprovider.UdemyCourseCategory'),
        ),
    ]
