# Generated by Django 2.1.5 on 2019-02-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentprovider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='udemycoursecategory',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='udemycoursecategory',
            name='title_cleaned',
        ),
        migrations.AddField(
            model_name='udemycoursecategory',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
