# Generated by Django 2.1.5 on 2019-02-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentprovider', '0002_auto_20190209_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseraRawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.TextField()),
                ('raw_data', models.TextField()),
                ('retrieved', models.DateTimeField(auto_now_add=True)),
                ('processed', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='udemycourse',
            name='primary_category',
        ),
        migrations.RemoveField(
            model_name='udemycourse',
            name='primary_subcategory',
        ),
        migrations.RemoveField(
            model_name='udemyinstructedby',
            name='course',
        ),
        migrations.RemoveField(
            model_name='udemyinstructedby',
            name='instructors',
        ),
        migrations.DeleteModel(
            name='UdemyCourse',
        ),
        migrations.DeleteModel(
            name='UdemyInstructedBy',
        ),
        migrations.DeleteModel(
            name='UdemyUser',
        ),
    ]
