# Generated by Django 2.1.5 on 2019-02-24 05:53

from django.db import migrations, models
import django.db.models.deletion
import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('contentprovider', '0003_auto_20190222_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='LyndaRawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.TextField()),
                ('retrieved', models.DateTimeField(auto_now_add=True)),
                ('processed', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UdemyRawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(core.models.DifficultyChoice(1), 1), (core.models.DifficultyChoice(2), 2), (core.models.DifficultyChoice(3), 3)])),
                ('duration', models.SmallIntegerField(choices=[(core.models.Duration(('short', 2)), 2), (core.models.Duration(('medium', 5)), 5), (core.models.Duration(('long', 12)), 12), (core.models.Duration(('extraLong', 22)), 22)])),
                ('page', models.SmallIntegerField(default=0)),
                ('raw_data', models.TextField()),
                ('retrieved', models.DateTimeField(auto_now_add=True)),
                ('processed', models.DateTimeField(blank=True, default=None, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentprovider.UdemyCourseCategory')),
            ],
        ),
    ]
