# Generated by Django 2.0.1 on 2019-05-02 08:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('psauth', '0003_usergoals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='courseuser',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='psauth.UserRole'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='usergoals',
            name='user',
        ),
        migrations.RemoveField(
            model_name='courseuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='courseuser',
            name='department',
        ),
        migrations.AddField(
            model_name='company',
            name='domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='UserGoals',
        ),
        migrations.AddField(
            model_name='userrole',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='psauth.Company'),
        ),
        migrations.AddField(
            model_name='organization',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='psauth.Company'),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suborg', to='psauth.Organization'),
        ),
        migrations.AddField(
            model_name='courseuser',
            name='org',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='psauth.Organization'),
        ),
    ]
