# Generated by Django 2.0.1 on 2019-02-22 04:18

from django.db import migrations, models
import learn.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseuserrelation',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Active', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[(learn.models.DifficultyChoice('Beginner'), 'Beginner'), (learn.models.DifficultyChoice('Intermediate'), 'Intermediate'), (learn.models.DifficultyChoice('Advanced'), 'Advanced'), (learn.models.DifficultyChoice('All'), 'All')], max_length=16, null=True),
        ),
    ]
