# Generated by Django 2.0.1 on 2019-01-20 06:25

from django.db import migrations, models
import learn.models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprovider',
            name='logo',
            field=models.ImageField(default='', upload_to=learn.models.CourseProvider.GetLogoFilename),
            preserve_default=False,
        ),
    ]
