# Generated by Django 2.1.5 on 2019-02-12 15:55

from django.db import migrations, models
import learn.models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.SmallIntegerField(choices=[(learn.models.DifficultyChoice(1), 1), (learn.models.DifficultyChoice(2), 2), (learn.models.DifficultyChoice(3), 3)], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
