# Generated by Django 2.0.1 on 2019-01-20 09:55

from django.db import migrations, models
import learn.models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_courseprovider_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[(learn.models.DifficultyChoice('Beginner'), 'Beginner'), (learn.models.DifficultyChoice('Intermediate'), 'Intermediate'), (learn.models.DifficultyChoice('Difficult'), 'Difficult'), (learn.models.DifficultyChoice('Very Difficult'), 'Very Difficult')], default='Beginner', max_length=16),
            preserve_default=False,
        ),
    ]
