# Generated by Django 2.1.5 on 2019-03-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_courseuserrelation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='extractor_version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
