# Generated by Django 2.1.5 on 2019-03-11 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_courseuserrelation_certificate'),
        ('learn', '0004_course_extractor_version'),
    ]

    operations = [
    ]
