# Generated by Django 2.0.1 on 2019-03-18 04:52

import core.models
from django.db import migrations, models
import django.db.models.deletion
import learn.models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_merge_20190311_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_students', models.SmallIntegerField(null=True)),
                ('min_students', models.SmallIntegerField(null=True)),
                ('session_count', models.SmallIntegerField(null=True)),
                ('prerequisites', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='mode',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.SmallIntegerField(choices=[(1, core.models.DifficultyChoice(1)), (2, core.models.DifficultyChoice(2)), (3, core.models.DifficultyChoice(3))]),
        ),
        migrations.AlterField(
            model_name='courseprovider',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=learn.models.CourseProvider.GetLogoFilename),
        ),
        migrations.AlterField(
            model_name='courseprovider',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='photo',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='livetraining',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='learn.Course'),
        ),
    ]
