# Generated by Django 2.0.1 on 2019-05-01 04:47

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0006_auto_20190318_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_goal', models.CharField(max_length=60)),
                ('difficulty', models.SmallIntegerField(choices=[(core.models.DifficultyChoice(1), 1), (core.models.DifficultyChoice(2), 2), (core.models.DifficultyChoice(3), 3)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
