# Generated by Django 2.0.1 on 2019-05-03 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psauth', '0005_organization_owner'),
        ('learn', '0007_usergoals'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoals',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='psauth.Company'),
            preserve_default=False,
        ),
    ]
