# Generated by Django 2.0.1 on 2019-05-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('learn', '0009_auto_20190503_1806'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseTag',
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(to='core.CourseTag'),
        ),
        migrations.AddField(
            model_name='objective',
            name='tags',
            field=models.ManyToManyField(to='core.CourseTag'),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='progressinpercent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
